# Generated by Django 4.0.5 on 2022-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('something', '0002_alter_url_options_alter_url_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_hash',
            field=models.URLField(default=None, unique=True, verbose_name='Хэш'),
        ),
    ]
