# Generated by Django 4.0.5 on 2022-07-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('something', '0003_url_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.URLField(unique=True, verbose_name='Хэш'),
        ),
    ]
